import Footer from "@/components/Footer";
import "./globals.css";
import Navbars from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Event Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbars /> */}
        <Navbars />
        {children}
        <Footer />
      </body>
    </html>
  );
}
