import Footer from "@/components/Footer";
import "./globals.css";
import Navbars from "@/components/Navbar";
import FacebookPixel from "./FacebookPixel";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Event Page",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>        
        <link rel='icon' href='./favicon.ico'/>

        <Navbars />
        {children}
        {/*  */}
        <Footer />
        <FacebookPixel/>
      </body>
    </html>
  );
}
